# Generated by Django 5.1.1 on 2025-01-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_service_image_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='services/default_service.png', null=True, upload_to='services/'),
        ),
    ]
